<a href="https://colab.research.google.com/github/EngRidhoNet/computer-vision-and-nlp/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
print(mylist)

[1, 2, 3]


In [6]:
myarray = np.array(mylist)

In [7]:
print(myarray)

[1 2 3]


In [8]:
type(myarray)

numpy.ndarray

In [11]:
np.arange(0,10,4)
# ini digunakan untuk langsung inisialisasi array dengan otomatis atau interval yang diberikan


array([0, 4, 8])

In [16]:
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
 np.random.seed(101)

In [6]:
arr = np.random.randint(0,100,10)
arr

array([49, 83,  8, 29, 59, 34, 44, 72, 19, 10])

In [11]:
# sebaliknya jika minimal gunakan variabel min()
print(arr.min())
print(arr.max())

8
83


In [13]:
# dan jika ingin tahu indeks nya ada dimana gunakan arg
print(arr.argmax())
print(arr.argmin())

1
2


In [14]:
# dan jika melakukan perhitungan rata rata gunakan mean
arr.mean()

40.7

In [15]:
# selanjutnya untuk mengetahui untuk ukuran dari array adalah dengan mengguanakan
arr.shape

(10,)

In [18]:
print("ini adalah isi dari array arr " + str(arr))

ini adalah isi dari array arr [49 83  8 29 59 34 44 72 19 10]


In [16]:
# sekarang kita akan ubah bentuknya dengan fungsi berikut
arr.reshape((2,5))

array([[49, 83,  8, 29, 59],
       [34, 44, 72, 19, 10]])